#########################
# FastAPI using pip
##########################
# Container configuration.

#   The name of this app. Must be unique within a project.
name: 'app'

#   The runtime the application uses.
type: 'python:3.11'

dependencies:
    python3:
       pipenv: '2023.2.4'

##########################
# Builds and variables

hooks:
    build: |
        set -eu

        # Download the latest version of pip
        python3.11 -m pip install --upgrade pip

        # Install dependencies
        pipenv install --deploy

##########################
# Web configuration

# The configuration of the application when it is exposed to the web.
web:
    commands:
        start: "pipenv run python src/server.py"

##########################
# Data and mounts

# The size of the persistent disk of the application (in MB).
disk: 3072

##########################
# Internal maintenance

source:
    operations:
        auto-update:
            command: |
              curl -fsS https://raw.githubusercontent.com/platformsh/source-operations/main/setup.sh | { bash /dev/fd/3 sop-autoupdate; } 3<&0
